---
- name: read temperature
  hosts: cluster

  tasks:

  - name: read temperature host processor
    ansible.builtin.command: cat /sys/class/thermal/thermal_zone0/temp
    register: temperature

  - name: print temperature (cast stdout onto int and divide)
    ansible.builtin.debug:
      msg: "Host: {{ hostvars[inventory_hostname].ansible_hostname }} temperature: {{ (temperature.stdout | int) / 1000 }} C"
