---
#k3s_version: v1.31.6+k3s1 <=== InPlacePodScaling does not work with this version
#k3s_version: v1.32.1+k3s1 <=== InPlacePodScaling does not work with this version
k3s_version: v1.32.3+k3s1

# ansible_user: ubuntu

# ansible_default_ipv4 - ref. https://medium.com/opsops/ansible-default-ipv4-is-not-what-you-think-edb8ab154b10
gateway: "{{ ansible_default_ipv4.gateway }}"

# IP of control node, token for worker access
# hostvars, groups, inventory_hostname - 
#    ref. https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
k3s_token: "{{ hostvars[groups['master'][0]]['token'] }}"

# worker_number is not used now, can be deleted, but let's keep as example of accessing inventory variables
#   notice 'index' is Jinja2 method here so the (.) notation is used to define the parameter list
worker_number: "{{ groups['node'].index(inventory_hostname) }}"
