---
k3s_version: v1.34.4+k3s1

# ansible_default_ipv4 - ref. https://medium.com/opsops/ansible-default-ipv4-is-not-what-you-think-edb8ab154b10
gateway: "{{ ansible_default_ipv4.gateway }}"

# IP address of the control node, k8s token for workers to access the control node
# hostvars, groups, inventory_hostname - 
#    ref. https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
k3s_token: "{{ hostvars[groups['master'][0]]['token'] }}"

# variable worker_number is not used now and can be deleted, but let's keep this as an example of accessing inventory variables
#   notice 'index' is Jinja2 method here so the (xyz) notation is used to define the parameter list
worker_number: "{{ groups['node'].index(inventory_hostname) }}"
