# This is only for educational purposes to analyse the magic var hostvars for selected host(s).
# To access access respective fields use index value/variable name in brackets [] if variable or
# element of array is referenced, i.e., [ index | <variable_name> ]; and for referencing 
# values of a map use either [' <key_name> '] or <dot><key_name> (i.e., .<key_name>) (so, the values
# in maps can be referenced in two alternative ways).

# NOTE1: To run this example it may be desired to limit the number of active hosts in the
# inventory because the output from Ansible can be verbose.
# NOTE2: If "var: hostvars" is left uncommented then only one host should be active in the
# inventory (errors are reported by Ansible otherwise).

# Run: ansible-playbook test_hostvars_fields.yaml -i inventory/hosts.ini

- hosts: cluster
  gather_facts: yes
  become: yes

  tasks:

  - name: Display all variables/facts known for a host
    debug:
#     Note: both two following forms work well and give the same result
#      var: hostvars[inventory_hostname]['ansible_facts']['distribution']
#      var: hostvars[inventory_hostname].ansible_facts.distribution

#     Note: this var produces very verbose output
      var: hostvars[inventory_hostname]

#     Note: hostvars alone does not work unless there's only one host active in the inventory
#      var: hostvars

#   Below, a couple of other examples of how to access various fields in hostvars

  - name: Host default address - "hostvars[inventory_hostname].ansible_default_ipv4.address"
    debug:
      msg: handled host is {{ inventory_hostname }} with default IPv4 {{hostvars[inventory_hostname].ansible_default_ipv4.address}}

  - name: All IPv4 addresses - hostvars[inventory_hostname].ansible_all_ipv4_addresses
    debug:
      var: hostvars[inventory_hostname].ansible_all_ipv4_addresses

  - name: Second IPv4 address - hostvars[inventory_hostname].ansible_all_ipv4_addresses[1]
    debug:
      var: hostvars[inventory_hostname].ansible_all_ipv4_addresses[1]

  - name: Next level - hostvars[inventory_hostname].ansible_eth0.features.esp_hw_offload
    debug:
      var: hostvars[inventory_hostname].ansible_eth0.features.esp_hw_offload

