---
# One needs to take care of ~/.ssh/cofig file with correct RbPi hostname/IP mapping.
# Normally, this is prepared by install.sh so no maual updates are needed, but in 
# case of problems check it. 

- hosts: cluster
  gather_facts: yes
  become: yes

  roles:
    - role: uninstall_master
    - role: uninstall_node
