- hosts: localhost

  tasks:
    - name: install k3s server
      debug:
        msg: >
          curl -sfL https://get.k3s.io |
          INSTALL_K3S_VERSION="1.32"
          INSTALL_K3S_EXEC="server
          --write-kubeconfig-mode 644 --disable servicelb --disable-cloud-controller
          --kube-apiserver-arg=feature-gates=InPlacePodVerticalScaling=true
          --kube-controller-manager-arg=feature-gates=InPlacePodVerticalScaling=true
          --kube-scheduler-arg=feature-gates=InPlacePodVerticalScaling=true
          --kubelet-arg=feature-gates=InPlacePodVerticalScaling=true
          --kube-proxy-arg=feature-gates=InPlacePodVerticalScaling=true"
          sh -s -

    - name: install k3s agent
      debug:
        msg: >
          curl -sfL https://get.k3s.io |
          INSTALL_K3S_VERSION="1.32"
          INSTALL_K3S_EXEC="agent
          --kubelet-arg=feature-gates=InPlacePodVerticalScaling=true
          --kube-proxy-arg=feature-gates=InPlacePodVerticalScaling=true"
          K3S_URL=https://192.168.10.51:6443
          K3S_TOKEN="k3s_token"
          K3S_KUBECONFIG_MODE="644"
          sh -s -
