---
- name: Set Ubuntu hostname for worker nodes
  # Hostname will be equal to the inventory_hostname, i.e. the name from hosts.ini file.
  hostname:
    name: "{{ inventory_hostname }}"
    #formerly was kpi09{{ worker_number|int + 2 }}

- name: Check if k3s already installed
  # not a thorough test - only existence of a directory
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s-agent on workers (agents)
  # note: K3s bundles its own containerd by default, no need to install it separately
  # setting feature-gate here enables InPlacePodVerticalScaling on cluster nodes
  shell:
    cmd: >
      curl -sfL https://get.k3s.io |
      INSTALL_K3S_VERSION={{ k3s_version }}
      INSTALL_K3S_EXEC="agent
      --kubelet-arg=feature-gates=InPlacePodVerticalScaling=true
      --kube-proxy-arg=feature-gates=InPlacePodVerticalScaling=true"      
      K3S_URL=https://{{ master_ip }}:6443
      K3S_TOKEN={{ k3s_token }}
      K3S_KUBECONFIG_MODE="644"
      sh -s -
    creates: /etc/rancher/k3s/k3s.yaml
  when: not k3s_installed.stat.exists
