---
- name: Set Ubuntu hostname for nodes (equal to the inventory_hostname, i.e. the name form hosts.yaml file)
  hostname:
    name: "{{ inventory_hostname }}"
    #formerly was kpi09{{ worker_number|int + 2 }}

- name: Check if k3s already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s-agent on workers (agents)
  shell:
    cmd: >
      curl -sfL https://get.k3s.io |
      INSTALL_K3S_VERSION={{ k3s_version }}
      INSTALL_K3S_EXEC="agent"
      K3S_URL=https://{{ master_ip }}:6443
      K3S_TOKEN={{ k3s_token }}
      K3S_KUBECONFIG_MODE="644"
      sh -s -
    creates: /etc/rancher/k3s/k3s.yaml
  when: not k3s_installed.stat.exists
